# Generated by Django 3.2.15 on 2022-09-14 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('dni', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=60)),
                ('responsabilidad', models.CharField(choices=[('REV', 'Revisor'), ('PREP', 'Preparador'), ('GER', 'Gerente')], max_length=10)),
                ('pais', models.CharField(choices=[('COL', 'COLOMBIA'), ('ARG', 'ARGENTINA'), ('MEX', 'MEXICO')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_razonsocial', models.CharField(max_length=10)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('numeroFormulario', models.CharField(max_length=6)),
                ('nombreFormulario', models.CharField(max_length=15)),
                ('n_verificacion', models.IntegerField()),
                ('periodo_fiscal', models.IntegerField()),
                ('año', models.IntegerField(choices=[('2021', '2021'), ('2022', '2021'), ('2023', '2021')])),
                ('saldoPagado', models.IntegerField()),
                ('saldoFavor', models.IntegerField()),
                ('pais', models.CharField(choices=[('COL', 'COLOMBIA'), ('ARG', 'ARGENTINA'), ('MEX', 'MEXICO')], max_length=3)),
                ('fecha_procesado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreimpuesto', models.CharField(max_length=10)),
                ('numero_fomr', models.CharField(max_length=6)),
                ('pais', models.CharField(choices=[('COL', 'COLOMBIA'), ('ARG', 'ARGENTINA'), ('MEX', 'MEXICO')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='VencimientoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('COL', 'COLOMBIA'), ('ARG', 'ARGENTINA'), ('MEX', 'MEXICO')], max_length=3)),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('año', models.IntegerField(choices=[('2021', '2021'), ('2022', '2021'), ('2023', '2021')])),
                ('nombre', models.CharField(max_length=20)),
                ('id_razonsocial', models.CharField(max_length=20)),
                ('nombre_empresa', models.CharField(max_length=20)),
                ('periodo_fiscal', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=50)),
                ('taxId', models.CharField(max_length=5)),
                ('nombreFormulario', models.CharField(max_length=20)),
                ('fechaVencimiento', models.DateTimeField()),
                ('fechaEntrega', models.DateTimeField()),
                ('fechaRevisado', models.DateTimeField()),
                ('review', models.CharField(max_length=60)),
                ('proceso', models.CharField(choices=[('PROCESADO', 'Procesado'), ('NO PROCESADO', 'No Procesado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('PROCESADO', 'Procesado'), ('FINALIZADO', 'Finalizado')], max_length=20)),
                ('idExtraccion', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.extraccion')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=50)),
                ('id_razonSocia', models.CharField(max_length=20)),
                ('pais', models.CharField(choices=[('COL', 'COLOMBIA'), ('ARG', 'ARGENTINA'), ('MEX', 'MEXICO')], max_length=3)),
                ('empleado', models.ManyToManyField(to='core.Empleado')),
                ('impuestos', models.ManyToManyField(to='core.Impuesto')),
            ],
        ),
    ]
