# Generated by Django 3.2.15 on 2022-09-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraccion',
            old_name='nombreFormulario',
            new_name='nombre_formulario',
        ),
        migrations.RenameField(
            model_name='extraccion',
            old_name='numeroFormulario',
            new_name='numero_formulario',
        ),
        migrations.RenameField(
            model_name='extraccion',
            old_name='saldoFavor',
            new_name='saldo_favor',
        ),
        migrations.RenameField(
            model_name='extraccion',
            old_name='saldoPagado',
            new_name='saldo_pagado',
        ),
        migrations.RenameField(
            model_name='impuesto',
            old_name='nombreimpuesto',
            new_name='nombre_impuesto',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='idExtraccion',
            new_name='id_extraccion',
        ),
        migrations.RenameField(
            model_name='vencimientoimpuesto',
            old_name='fechaEntrega',
            new_name='fecha_entrega',
        ),
        migrations.RenameField(
            model_name='vencimientoimpuesto',
            old_name='fechaRevisado',
            new_name='fecha_revisado',
        ),
        migrations.RenameField(
            model_name='vencimientoimpuesto',
            old_name='fechaVencimiento',
            new_name='fecha_vencimiento',
        ),
        migrations.RenameField(
            model_name='vencimientoimpuesto',
            old_name='nombreFormulario',
            new_name='nombre_formulario',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='numero_fomr',
        ),
        migrations.AddField(
            model_name='impuesto',
            name='numero_fomulario',
            field=models.CharField(blank=True, choices=[(731, 'Argentina'), (300, 'Colombia'), (1, 'Mexico')], default='', max_length=3),
        ),
    ]
