# Generated by Django 3.2.15 on 2022-09-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220914_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='pais',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('COL', 'Colombia'), ('MEX', 'Mexico')], max_length=3),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('COL', 'Colombia'), ('MEX', 'Mexico')], max_length=3),
        ),
        migrations.AlterField(
            model_name='extraccion',
            name='pais',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('COL', 'Colombia'), ('MEX', 'Mexico')], max_length=3),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='pais',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('COL', 'Colombia'), ('MEX', 'Mexico')], max_length=3),
        ),
        migrations.AlterField(
            model_name='vencimientoimpuesto',
            name='pais',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('COL', 'Colombia'), ('MEX', 'Mexico')], max_length=3),
        ),
    ]
