# Generated by Django 3.2.15 on 2022-09-17 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220914_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='id_razonSocia',
            new_name='id_razonSocial',
        ),
        migrations.AddField(
            model_name='documento',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='numero_fomulario',
            field=models.CharField(blank=True, choices=[('731', 'Argentina 731'), ('300', 'Colombia 300'), ('001', 'Mexico 001')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Procesado', 'Procesado'), ('Finalizado', 'Finalizado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='id_extraccion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.extraccion'),
        ),
    ]
