# Generated by Django 3.2.15 on 2022-09-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220917_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraccion',
            name='n_verificacion',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='extraccion',
            name='saldo_favor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='extraccion',
            name='saldo_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Procesado', 'Procesado'), ('Finalizado', 'Finalizado'), ('Fallido', 'Fallido')], max_length=20),
        ),
    ]
