# Generated by Django 3.2.15 on 2022-09-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220925_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraccion',
            name='id_razonsocial',
            field=models.CharField(max_length=20),
        ),
    ]
