# Generated by Django 3.2.15 on 2022-09-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_extraccion_id_razonsocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vencimientoimpuesto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='vencimientoimpuesto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='vencimientoimpuesto',
            name='taxId',
        ),
        migrations.AlterField(
            model_name='vencimientoimpuesto',
            name='proceso',
            field=models.CharField(choices=[(1, 'Procesado'), (2, 'No Procesado')], max_length=20),
        ),
    ]
