# Generated by Django 3.2.15 on 2022-09-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220927_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vencimientoimpuesto',
            name='id_razonsocial',
            field=models.CharField(max_length=30),
        ),
    ]
