# Generated by Django 3.2.15 on 2022-09-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_vencimientoimpuesto_id_razonsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vencimientoimpuesto',
            name='proceso',
            field=models.CharField(choices=[('PROCESADO', 'Procesado'), ('NO PROCESADO', 'No Procesado')], max_length=50),
        ),
    ]
