# Generated by Django 3.2.15 on 2022-09-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_vencimientoimpuesto_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vencimientoimpuesto',
            name='proceso',
            field=models.CharField(choices=[('Procesado', 'Procesado'), ('No Procesado', 'No Procesado')], max_length=50),
        ),
    ]
