# Generated by Django 3.2.15 on 2022-10-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_vencimientoimpuesto_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vencimientoimpuesto',
            name='fecha_entrega',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vencimientoimpuesto',
            name='fecha_revisado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vencimientoimpuesto',
            name='fecha_vencimiento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vencimientoimpuesto',
            name='mes',
            field=models.IntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')]),
        ),
        migrations.AlterField(
            model_name='vencimientoimpuesto',
            name='nombre_empresa',
            field=models.CharField(default='', max_length=50),
        ),
    ]
